do not convert cluster_encryption_config into set
 Error: Invalid dynamic for_each value
│ 
│   on .terraform/modules/eks-runners.eks/cluster.tf line 35, in resource "aws_eks_cluster" "this":
│   35:     for_each = toset(var.cluster_encryption_config)
│     ├────────────────
│     │ var.cluster_encryption_config is list of object with 1 element
│ 
│ Cannot use a set of object value in for_each. An iterable collection is required.