aws bug: use dynamic tag instead of tags in ASG
```
Error: Provider produced inconsistent final plan

When expanding the plan for module.eks.aws_autoscaling_group.workers[0] to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags:
length changed from 4 to 6.
```

https://github.com/terraform-providers/terraform-provider-aws/issues/14085